---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: softsparq-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-cosmic # ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

platforms:
  - linux/amd64

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: custom-kernel
    source: local
    kernel: cachyos-lto
    secrets:
      - type: file
        source: .secure_files/MOK.priv
        mount:
          type: file
          destination: /tmp/certs/MOK.priv
    sign:
      key: /tmp/certs/MOK.priv
      cert: /usr/share/cert/MOK.pem
      mok-password: origami

  - from-file: core.yml

  - type: os-release
    properties:
      ID: softsparq-os
      ID_LIKE: fedora
      NAME: Softsparq OS
      PRETTY_NAME: Softsparq OS
      HOME_URL: "https://origami.wf/"
      BUG_REPORT_URL: "https://gitlab.com/groups/origami-linux/-/issues"
      DEFAULT_HOSTNAME: softsparq

  - type: initramfs

  - type: signing
